### ISSUE TITLE
add something to the blueprint that installs "ember-algolia" and "algoliasearch" into the consuming app

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-learn-search-components#5]
I'm not entirely sure how to get an addon to install dependencies in the consuming app once it's installed 😖 

this would actually solve the issue of the algolia key setup in the consuming app environment (I think)

**Comment by acorncom** [comment]
Although we *could* have the dependencies installed by the consuming app (instead of this addon), I don’t think I want to. If/when this addon is installed in 4+ Ember apps we manage, do we really want to have to touch each one to bump the `ember-algolia` dependency? I’m quite happy to have that all managed through this addon ...

**Comment by jaredgalanis** [comment]
We're closing this because the only repos which consume this tool are archived/deprecated. Thank you for your interest in contributing to the Ember project!
